services:

  postgres:
    image: postgres:latest
    container_name: postgreSQL
    environment:
      POSTGRES_DB: trading-app
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader -d trading-app"]
      interval: 10s  # health check in every 10 sec
      timeout: 5s # Timeout for each healthcheck (Health check must be completed within 5 sec)
      retries: 3 # Retry up to 3 times before marking as unhealthy
      start_period: 10s # This is a delay (10 seconds) after container startup before Docker begins checking the service health, giving PostgreSQL some time to initialize
    networks:
      - trading_network

  app:
    image: trading-app
    container_name: trading-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgreSQL:5432/trading-app
      - SPRING_DATASOURCE_USERNAME=trader
      - SPRING_DATASOURCE_PASSWORD=12345
    ports:
      - "8080:8080"
    depends_on:
      postgres:
          condition: service_healthy
    networks:
      - trading_network

networks:
  trading_network: