spring:
  application:
    name: tradingPlatform
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/trading-app
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver


server:
  port: 8080


